version: "3"

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  users:
    build: ./users
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  orders:
    build: ./orders
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  payments:
    build: ./payments
    ports:
      - "3003:3003"
    depends_on:
      - mongo
